import type { Checklist } from '../types';

export const checklists: Checklist[] = [
  {
    id: 'kitchen-launch',
    title: 'Kitchen Launch Checklist',
    description: 'Soft launch-এর আগে যা যা final থাকা দরকার।',
    phase: 'operations',
    items: [
      { id: 'loc', label: 'Kitchen location final' },
      { id: 'rent', label: 'Rent agreement signed' },
      { id: 'fssai', label: 'FSSAI registration/license (official portal-এ verify করা)' },
      { id: 'safety', label: 'Fire extinguisher + LPG safety setup' },
      { id: 'equipment', label: 'Core equipment installed ও tested' },
      { id: 'supplier', label: 'Raw material supplier + backup supplier confirm' },
      { id: 'packaging', label: 'Packaging finalised ও leak-test পাস' },
      { id: 'menu', label: 'Launch menu locked' },
      { id: 'recipe-sop', label: 'প্রতিটি dish-এর Recipe SOP লেখা' },
      { id: 'photos', label: 'Food photography — সব hero dish' },
      { id: 'zomato', label: 'Zomato onboarding সম্পূর্ণ' },
      { id: 'swiggy', label: 'Swiggy onboarding সম্পূর্ণ' },
      { id: 'soft-launch', label: 'Soft launch (সীমিত radius/hours)' },
      { id: 'first-10', label: 'First 10 orders সম্পন্ন ও review করা' },
      { id: 'first-50', label: 'First 50 orders — SOP গ্যাপ চিহ্নিত' },
      { id: 'first-100', label: 'First 100 orders / reviews milestone' },
    ],
  },
  {
    id: 'daily-open',
    title: 'Opening Kitchen SOP Checklist',
    description: 'প্রতিদিন service শুরুর আগে।',
    phase: 'operations',
    items: [
      { id: 'clean', label: 'Work surface ও equipment sanitised' },
      { id: 'gas', label: 'LPG connection ও burner leak-check' },
      { id: 'fridge-temp', label: 'Refrigerator/freezer temperature লগ করা' },
      { id: 'stock', label: 'Perishable stock ও prep quantity যাচাই' },
      { id: 'packaging-stock', label: 'Packaging ও label stock যথেষ্ট' },
      { id: 'prep', label: 'Base gravy / marination / cut veg prep সম্পন্ন' },
      { id: 'platform-online', label: 'Zomato ও Swiggy outlet online করা' },
      { id: 'test-order', label: '(সপ্তাহে একবার) নিজে test order দিয়ে flow যাচাই' },
    ],
  },
  {
    id: 'daily-close',
    title: 'Closing Kitchen SOP Checklist',
    description: 'প্রতিদিন service শেষে।',
    phase: 'operations',
    items: [
      { id: 'offline', label: 'Platform outlet offline করা' },
      { id: 'closing-stock', label: 'Closing stock গণনা ও লগ' },
      { id: 'wastage', label: 'Wastage রেকর্ড করা (কারণসহ)' },
      { id: 'fridge', label: 'Perishables ঠিকভাবে সংরক্ষণ / label' },
      { id: 'clean-deep', label: 'Deep clean — stove, exhaust filter, floor, bins' },
      { id: 'gas-off', label: 'LPG regulator বন্ধ, electrical বন্ধ' },
      { id: 'daybook', label: 'Day-book: orders, revenue, complaints নোট' },
      { id: 'reorder', label: 'Reorder level-এ থাকা item-এর purchase list তৈরি' },
    ],
  },
  {
    id: 'compliance',
    title: 'Compliance Checklist',
    description: 'আইনি ও নিরাপত্তা — নিয়ম পরিবর্তনশীল, official source verify করো।',
    phase: 'phase-04',
    items: [
      { id: 'fssai-status', label: 'FSSAI registration/license সঠিক category-তে আছে' },
      { id: 'fssai-display', label: 'FSSAI number menu/packaging-এ display করা' },
      { id: 'gst-check', label: 'GST registration দরকার কিনা — official source-এ যাচাই' },
      { id: 'trade', label: 'Local municipal / trade license প্রয়োজন কিনা যাচাই' },
      { id: 'fire', label: 'Fire safety requirement যাচাই ও extinguisher servicing' },
      { id: 'lpg', label: 'Commercial LPG connection ও safety compliance' },
      { id: 'water', label: 'Potable water source ও pest control ব্যবস্থা' },
      { id: 'renewal', label: 'সব license-এর renewal date একটি জায়গায় লেখা' },
    ],
  },
];
