import type { DocMeta } from '../types';

import whatIs from './docs/what-is-dipikar-rannghor.md?raw';
import howToUse from './docs/how-to-use-this-app.md?raw';
import ckVsRestaurant from './docs/cloud-kitchen-vs-restaurant.md?raw';
import competitorResearch from './docs/competitor-research.md?raw';
import kitchenLocation from './docs/kitchen-location.md?raw';
import fssaiGst from './docs/fssai-and-gst.md?raw';
import menuEngineering from './docs/menu-engineering-basics.md?raw';
import foodCost from './docs/food-cost-fundamentals.md?raw';
import breakEven from './docs/break-even-basics.md?raw';
import orderOps from './docs/order-operations-flow.md?raw';
import equipmentPlanning from './docs/equipment-planning.md?raw';
import sopSystem from './docs/sop-system.md?raw';
import packagingTesting from './docs/packaging-testing.md?raw';
import zomatoOnboarding from './docs/zomato-onboarding.md?raw';
import swiggyOnboarding from './docs/swiggy-onboarding.md?raw';
import pricingStrategy from './docs/pricing-strategy.md?raw';
import marketingOrganic from './docs/marketing-organic-first.md?raw';
import financeTracking from './docs/finance-tracking.md?raw';
import reviewManagement from './docs/customer-review-management.md?raw';

export const documents: DocMeta[] = [
  {
    id: 'what-is-dipikar-rannghor',
    slug: 'what-is-dipikar-rannghor',
    title: 'Dipikar Rannghor কী?',
    summary: 'এই app কী জন্য, Learn → Do → Verify → Document loop, আর Learning বনাম Execution progress।',
    phase: 'phase-00',
    category: 'Foundation',
    tags: ['getting-started', 'overview', 'philosophy'],
    difficulty: 'beginner',
    readingMinutes: 4,
    relatedDocs: ['how-to-use-this-app', 'cloud-kitchen-vs-restaurant'],
    relatedTasks: ['t-budget'],
    content: whatIs,
  },
  {
    id: 'how-to-use-this-app',
    slug: 'how-to-use-this-app',
    title: 'এই app কীভাবে ব্যবহার করবে',
    summary: 'প্রতিটি section-এর কাজ, search, filter, progress ও backup — এক নজরে।',
    phase: 'phase-00',
    category: 'Foundation',
    tags: ['getting-started', 'search', 'filters', 'backup'],
    difficulty: 'beginner',
    readingMinutes: 3,
    relatedDocs: ['what-is-dipikar-rannghor'],
    relatedTasks: ['t-decision-log'],
    content: howToUse,
  },
  {
    id: 'cloud-kitchen-vs-restaurant',
    slug: 'cloud-kitchen-vs-restaurant',
    title: 'Cloud Kitchen বনাম Restaurant',
    summary: 'Fixed cost, staffing, break-even ও platform-নির্ভরতা — কোথায় দুটো model আলাদা।',
    phase: 'phase-01',
    category: 'Foundation',
    tags: ['business-model', 'fixed-cost', 'delivery'],
    difficulty: 'beginner',
    readingMinutes: 5,
    relatedDocs: ['competitor-research', 'kitchen-location', 'break-even-basics'],
    relatedTasks: ['t-niche'],
    content: ckVsRestaurant,
  },
  {
    id: 'competitor-research',
    slug: 'competitor-research',
    title: 'Competitor Research — ২০টি competitor',
    summary: 'Zomato/Swiggy থেকে ২০টি competitor-এর price, rating, review ও menu analyse করে market gap বের করা।',
    phase: 'phase-02',
    category: 'Market Research',
    tags: ['zomato', 'swiggy', 'competitor', 'market-gap', 'pricing'],
    difficulty: 'beginner',
    readingMinutes: 6,
    relatedDocs: ['cloud-kitchen-vs-restaurant', 'menu-engineering-basics', 'food-cost-fundamentals'],
    relatedTasks: ['t-competitor-20', 't-market-gap', 't-value-prop'],
    content: competitorResearch,
  },
  {
    id: 'kitchen-location',
    slug: 'kitchen-location',
    title: 'Kitchen Location নির্বাচন',
    summary: 'Delivery radius coverage, rent বনাম order density, LPG ও exhaust feasibility, rider access।',
    phase: 'phase-03',
    category: 'Location & Kitchen',
    tags: ['location', 'rent', 'delivery-radius', 'lpg', 'exhaust'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['cloud-kitchen-vs-restaurant', 'fssai-and-gst', 'break-even-basics'],
    relatedTasks: ['t-location-shortlist', 't-layout'],
    content: kitchenLocation,
  },
  {
    id: 'fssai-and-gst',
    slug: 'fssai-and-gst',
    title: 'FSSAI ও GST — কী যাচাই করবে',
    summary: 'নিয়ম পরিবর্তনশীল — এই পাতা শুধু official source-এ কী যাচাই করতে হবে তা বলে।',
    phase: 'phase-04',
    category: 'Legal & Compliance',
    tags: ['fssai', 'gst', 'compliance', 'license', 'verify'],
    difficulty: 'intermediate',
    readingMinutes: 5,
    relatedDocs: ['kitchen-location', 'order-operations-flow'],
    relatedTasks: ['t-fssai', 't-gst-check'],
    content: fssaiGst,
  },
  {
    id: 'menu-engineering-basics',
    slug: 'menu-engineering-basics',
    title: 'Menu Engineering — মূল ধারণা',
    summary: 'Popularity × Contribution grid, hero products, combos ও add-ons, portion fix, dish template।',
    phase: 'menu',
    category: 'Menu',
    tags: ['menu', 'hero-product', 'combo', 'portion', 'contribution'],
    difficulty: 'intermediate',
    readingMinutes: 7,
    relatedDocs: ['competitor-research', 'food-cost-fundamentals', 'break-even-basics'],
    relatedTasks: ['t-recipe-sop', 't-food-cost'],
    content: menuEngineering,
  },
  {
    id: 'food-cost-fundamentals',
    slug: 'food-cost-fundamentals',
    title: 'Food Cost Fundamentals',
    summary: 'Food Cost %, platform commission ও packaging একসাথে ধরে per-order contribution বের করা — worked example সহ।',
    phase: 'costing',
    category: 'Finance',
    tags: ['food-cost', 'contribution', 'commission', 'packaging', 'calculator'],
    difficulty: 'intermediate',
    readingMinutes: 7,
    relatedDocs: ['menu-engineering-basics', 'break-even-basics', 'competitor-research'],
    relatedTasks: ['t-food-cost'],
    content: foodCost,
  },
  {
    id: 'break-even-basics',
    slug: 'break-even-basics',
    title: 'Break-even Basics',
    summary: 'দিনে কতগুলো order না হলে লোকসান — fixed cost, contribution ও AOV দিয়ে হিসাব।',
    phase: 'costing',
    category: 'Finance',
    tags: ['break-even', 'fixed-cost', 'aov', 'discount', 'calculator'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['food-cost-fundamentals', 'menu-engineering-basics', 'kitchen-location'],
    relatedTasks: ['t-breakeven'],
    content: breakEven,
  },
  {
    id: 'order-operations-flow',
    slug: 'order-operations-flow',
    title: 'Order Operations Flow',
    summary: 'Order Received → … → Review — প্রতিটা stage-এর responsibility, time, failure ও checklist।',
    phase: 'operations',
    category: 'Operations',
    tags: ['operations', 'kot', 'quality-check', 'packaging', 'handover'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['menu-engineering-basics'],
    relatedTasks: ['t-packaging-test', 't-soft-launch'],
    content: orderOps,
  },
  {
    id: 'equipment-planning',
    slug: 'equipment-planning',
    title: 'Equipment Planning — must-have vs later',
    summary: 'প্রতিটি equipment-এর কেন/কখন/spec/budget/alternative/mistake, আর launch-এর আগে ঠিক কতটুকু লাগে।',
    phase: 'phase-05',
    category: 'Equipment',
    tags: ['equipment', 'lpg', 'exhaust', 'budget', 'kitchen-setup'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['kitchen-location', 'order-operations-flow', 'break-even-basics'],
    relatedTasks: ['t-equipment-list'],
    content: equipmentPlanning,
  },
  {
    id: 'sop-system',
    slug: 'sop-system',
    title: 'SOP System — quality repeatable করা',
    summary: 'SOP format, কোন SOP আগে দরকার, আর SOP লিখে test করে গ্যাপ বন্ধ করা।',
    phase: 'operations',
    category: 'Operations',
    tags: ['sop', 'quality', 'standardization', 'training', 'checklist'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['order-operations-flow', 'menu-engineering-basics', 'food-cost-fundamentals'],
    relatedTasks: ['t-recipe-sop'],
    content: sopSystem,
  },
  {
    id: 'packaging-testing',
    slug: 'packaging-testing',
    title: 'Packaging Testing ও Scoring',
    summary: 'Leak, heat retention, transport ও stacking test করে ২–৩টি packaging option-কে score করা।',
    phase: 'operations',
    category: 'Operations',
    tags: ['packaging', 'leak-test', 'heat-retention', 'cost', 'food-safety'],
    difficulty: 'beginner',
    readingMinutes: 5,
    relatedDocs: ['order-operations-flow', 'food-cost-fundamentals', 'sop-system'],
    relatedTasks: ['t-packaging-test'],
    content: packagingTesting,
  },
  {
    id: 'zomato-onboarding',
    slug: 'zomato-onboarding',
    title: 'Zomato Onboarding',
    summary: 'কী document লাগে, listing quality কোথায় জেতা/হারা যায়, self test order দিয়ে verify।',
    phase: 'operations',
    category: 'Operations',
    tags: ['zomato', 'onboarding', 'listing', 'photos', 'commission', 'verify'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['swiggy-onboarding', 'menu-engineering-basics', 'order-operations-flow', 'fssai-and-gst'],
    relatedTasks: ['t-zomato-onboard', 't-photos'],
    content: zomatoOnboarding,
  },
  {
    id: 'swiggy-onboarding',
    slug: 'swiggy-onboarding',
    title: 'Swiggy Onboarding',
    summary: 'Zomato থেকে পার্থক্য কোথায় — menu mapping, pricing parity সিদ্ধান্ত, payout ও rating system।',
    phase: 'operations',
    category: 'Operations',
    tags: ['swiggy', 'onboarding', 'menu-mapping', 'pricing-parity', 'payout', 'verify'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['zomato-onboarding', 'pricing-strategy', 'customer-review-management'],
    relatedTasks: ['t-swiggy-onboard'],
    content: swiggyOnboarding,
  },
  {
    id: 'pricing-strategy',
    slug: 'pricing-strategy',
    title: 'Pricing Strategy — MVSP ও discount economics',
    summary: 'Cost-plus / market / value / psychological একসাথে; Minimum Viable Selling Price; discount কখন ক্ষতি।',
    phase: 'costing',
    category: 'Finance',
    tags: ['pricing', 'mvsp', 'discount', 'combo', 'contribution-margin'],
    difficulty: 'intermediate',
    readingMinutes: 7,
    relatedDocs: ['food-cost-fundamentals', 'break-even-basics', 'competitor-research', 'menu-engineering-basics'],
    relatedTasks: ['t-food-cost', 't-breakeven'],
    content: pricingStrategy,
  },
  {
    id: 'marketing-organic-first',
    slug: 'marketing-organic-first',
    title: 'Marketing — Organic First',
    summary: 'Product → listing → organic validation → তারপর paid। Pre-paid checklist ও tracking sheet।',
    phase: 'growth',
    category: 'Marketing',
    tags: ['marketing', 'organic', 'reviews', 'brand', 'paid-acquisition', 'retention'],
    difficulty: 'beginner',
    readingMinutes: 6,
    relatedDocs: ['zomato-onboarding', 'customer-review-management', 'break-even-basics'],
    relatedTasks: ['t-photos'],
    content: marketingOrganic,
  },
  {
    id: 'finance-tracking',
    slug: 'finance-tracking',
    title: 'Finance Tracking — Daily / Weekly / Monthly',
    summary: 'রোজ ৫ মিনিট, সপ্তাহে ১৫, মাসে P&L — এবং actual বনাম projected break-even মেলানো।',
    phase: 'growth',
    category: 'Finance',
    tags: ['finance', 'p&l', 'tracking', 'commission', 'wastage', 'break-even'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['break-even-basics', 'food-cost-fundamentals', 'customer-review-management'],
    relatedTasks: ['t-breakeven'],
    content: financeTracking,
  },
  {
    id: 'customer-review-management',
    slug: 'customer-review-management',
    title: 'Customer & Review Management',
    summary: 'Review tag করা → top প্যাটার্ন → নির্দিষ্ট SOP fix → পরের সপ্তাহে verify। Repeat rate = সৎ metric।',
    phase: 'growth',
    category: 'Customer',
    tags: ['reviews', 'rating', 'complaints', 'repeat-rate', 'sop', 'improvement'],
    difficulty: 'intermediate',
    readingMinutes: 6,
    relatedDocs: ['order-operations-flow', 'sop-system', 'marketing-organic-first', 'finance-tracking'],
    relatedTasks: ['t-soft-launch'],
    content: reviewManagement,
  },
];

export const docBySlug = Object.fromEntries(documents.map((d) => [d.slug, d]));
