import type { TaskSeed } from '../types';

/** Seed backlog — the "what should I actually do" spine of the app. */
export const taskSeeds: TaskSeed[] = [
  {
    id: 't-budget',
    task: 'Initial budget planning sheet তৈরি করা (setup cost + ৩ মাসের running cost buffer)',
    category: 'Foundation',
    phase: 'phase-00',
    priority: 'critical',
    status: 'todo',
    completionCriteria: 'এক পাতায় total setup cost, monthly fixed cost ও ৩ মাসের survival buffer লেখা আছে।',
  },
  {
    id: 't-decision-log',
    task: 'প্রথম ৩টি major decision Decision Log-এ লেখা (cuisine, area, budget ceiling)',
    category: 'Foundation',
    phase: 'phase-00',
    priority: 'high',
    status: 'todo',
    completionCriteria: 'Decision Log-এ অন্তত ৩টি entry, প্রতিটিতে reason ও date আছে।',
  },
  {
    id: 't-value-prop',
    task: 'এক বাক্যে value proposition লেখা: "কার জন্য, কোন সমস্যার সমাধান, কেন আমরা"',
    category: 'Foundation',
    phase: 'phase-01',
    priority: 'high',
    status: 'todo',
    dependency: 't-competitor-20',
    completionCriteria: 'একটি স্পষ্ট এক-বাক্যের statement লেখা যা target customer ও differentiation বলে।',
  },
  {
    id: 't-niche',
    task: 'Cuisine ও niche shortlist (৩টি option) → competitor density ও food cost দেখে ১টি বেছে নেওয়া',
    category: 'Foundation',
    phase: 'phase-01',
    priority: 'critical',
    status: 'todo',
    completionCriteria: '১টি primary cuisine + niche final, কারণসহ Decision Log-এ নথিভুক্ত।',
  },
  {
    id: 't-competitor-20',
    task: 'নিজের এলাকার Zomato/Swiggy থেকে ২০টি competitor analyse করা (price, rating, review, menu size, best-sellers)',
    category: 'Market Research',
    phase: 'phase-02',
    priority: 'critical',
    status: 'todo',
    notes: 'Documentation → "Competitor Research" এর template ব্যবহার করো।',
    completionCriteria: '২০ সারির একটি competitor matrix ভরা, top 5 ও তাদের weakness চিহ্নিত।',
  },
  {
    id: 't-market-gap',
    task: 'Competitor matrix থেকে ৩টি market gap লেখা এবং কোনটা attack করব ঠিক করা',
    category: 'Market Research',
    phase: 'phase-02',
    priority: 'high',
    status: 'todo',
    dependency: 't-competitor-20',
    completionCriteria: '৩টি gap লেখা, ১টি বেছে নেওয়া হয়েছে reason সহ।',
  },
  {
    id: 't-location-shortlist',
    task: 'Kitchen-এর জন্য ৩টি সম্ভাব্য location shortlist (rent, deposit, delivery radius coverage, LPG/exhaust সম্ভাব্যতা)',
    category: 'Location & Kitchen',
    phase: 'phase-03',
    priority: 'high',
    status: 'backlog',
    completionCriteria: '৩টি location-এর তুলনামূলক টেবিল, প্রতিটির pros/cons সহ।',
  },
  {
    id: 't-layout',
    task: 'একটি practical kitchen layout আঁকা — cooking / prep / packaging / storage / cleaning zone আলাদা করে',
    category: 'Location & Kitchen',
    phase: 'phase-03',
    priority: 'medium',
    status: 'backlog',
    dependency: 't-location-shortlist',
    completionCriteria: 'হাতে-আঁকা বা ডিজিটাল একটি zone-wise layout, workflow তীর সহ।',
  },
  {
    id: 't-fssai',
    task: 'FSSAI-এর সঠিক category (Registration / State License) official portal-এ যাচাই করে apply করা',
    category: 'Legal & Compliance',
    phase: 'phase-04',
    priority: 'critical',
    status: 'backlog',
    notes: 'কোনো YouTube video-র পুরনো তথ্য blindly follow করবে না।',
    completionCriteria: 'Application submitted, acknowledgement number সংরক্ষিত।',
  },
  {
    id: 't-gst-check',
    task: 'নিজের ক্ষেত্রে GST registration লাগবে কিনা official source / CA-র সঙ্গে যাচাই করা',
    category: 'Legal & Compliance',
    phase: 'phase-04',
    priority: 'high',
    status: 'backlog',
    completionCriteria: 'সিদ্ধান্ত ও তার ভিত্তি Decision Log-এ লেখা।',
  },
  {
    id: 't-equipment-list',
    task: 'Equipment list + approximate budget তৈরি করা (must-have vs later)',
    category: 'Equipment',
    phase: 'phase-05',
    priority: 'high',
    status: 'backlog',
    completionCriteria: 'প্রতিটি item-এ spec, budget, must-have/later ট্যাগ আছে।',
  },
  {
    id: 't-recipe-sop',
    task: 'Hero dish-এর জন্য পূর্ণ Recipe SOP লেখা (গ্রামে ingredient, ধাপ, সময়, quality check)',
    category: 'Menu',
    phase: 'menu',
    priority: 'critical',
    status: 'backlog',
    completionCriteria: 'অন্তত ২টি hero dish-এর standardized recipe, ৩ বার রান্না করে স্বাদ consistent।',
  },
  {
    id: 't-food-cost',
    task: 'প্রতিটি menu item-এর food cost ও Food Cost % হিসাব করা (নিজের ingredient দাম দিয়ে)',
    category: 'Finance',
    phase: 'costing',
    priority: 'critical',
    status: 'backlog',
    dependency: 't-recipe-sop',
    completionCriteria: 'সব item-এর জন্য food cost, packaging cost, contribution ও Food Cost % একটি sheet-এ।',
  },
  {
    id: 't-breakeven',
    task: 'Break-even calculator-এ নিজের সংখ্যা বসিয়ে break-even orders/day বের করা',
    category: 'Finance',
    phase: 'costing',
    priority: 'high',
    status: 'backlog',
    dependency: 't-food-cost',
    completionCriteria: 'Break-even orders/day জানা এবং সেটা realistic কিনা যাচাই করা হয়েছে।',
  },
  {
    id: 't-packaging-test',
    task: '২–৩ ধরনের packaging কিনে leak / heat-retention / transport test করে score করা',
    category: 'Operations',
    phase: 'operations',
    priority: 'medium',
    status: 'backlog',
    completionCriteria: 'একটি scoring টেবিল, বিজয়ী packaging বেছে নেওয়া হয়েছে।',
  },
  {
    id: 't-supplier-compare',
    task: 'মূল ৫টি raw material-এর জন্য অন্তত ২ জন করে supplier compare করা (price, quality, MOQ, delivery)',
    category: 'Procurement',
    phase: 'operations',
    priority: 'high',
    status: 'backlog',
    completionCriteria: 'Supplier comparison টেবিল ভরা, primary + backup ঠিক করা।',
  },
  {
    id: 't-photos',
    task: 'সব hero dish-এর ভালো food photography (natural light, consistent framing)',
    category: 'Marketing',
    phase: 'growth',
    priority: 'high',
    status: 'backlog',
    dependency: 't-recipe-sop',
    completionCriteria: 'প্রতিটি listing item-এর জন্য অন্তত ১টি ব্যবহারযোগ্য ছবি।',
  },
  {
    id: 't-zomato-onboard',
    task: 'Zomato partner onboarding — current official partner documentation দেখে সব তথ্য জমা',
    category: 'Operations',
    phase: 'operations',
    priority: 'critical',
    status: 'backlog',
    dependency: 't-fssai',
    completionCriteria: 'Listing live, menu ও pricing verify করা।',
  },
  {
    id: 't-swiggy-onboard',
    task: 'Swiggy partner onboarding — current official partner documentation দেখে সব তথ্য জমা',
    category: 'Operations',
    phase: 'operations',
    priority: 'critical',
    status: 'backlog',
    dependency: 't-fssai',
    completionCriteria: 'Listing live, menu ও pricing verify করা।',
  },
  {
    id: 't-pricing-decision',
    task: 'প্রতিটি hero item-এর MVSP বের করে launch price ঠিক করা ও Decision Log-এ লেখা',
    category: 'Finance',
    phase: 'costing',
    priority: 'high',
    status: 'backlog',
    dependency: 't-food-cost',
    completionCriteria: 'প্রতিটি hero item-এর MVSP, launch price ও কারণ Decision Log-এ নথিভুক্ত।',
  },
  {
    id: 't-finance-sheet',
    task: 'Daily / Weekly / Monthly finance tracking sheet তৈরি করে আজ থেকে Daily row ভরা শুরু করা',
    category: 'Finance',
    phase: 'growth',
    priority: 'high',
    status: 'backlog',
    completionCriteria: 'তিন-tab sheet তৈরি এবং অন্তত ৩ দিনের Daily entry আছে।',
  },
  {
    id: 't-review-ritual',
    task: 'Weekly review-ritual সেট করা: review tag করা → top প্যাটার্ন → একটি SOP fix',
    category: 'Customer',
    phase: 'growth',
    priority: 'medium',
    status: 'backlog',
    dependency: 't-soft-launch',
    completionCriteria: 'Review-tracking sheet তৈরি, প্রথম weekly review সম্পন্ন, একটি SOP পরিবর্তন প্রয়োগ।',
  },
  {
    id: 't-soft-launch',
    task: 'Soft launch — সীমিত radius ও সীমিত hours-এ প্রথম real order নেওয়া',
    category: 'Operations',
    phase: 'operations',
    priority: 'critical',
    status: 'backlog',
    dependency: 't-zomato-onboard',
    completionCriteria: 'অন্তত ১০টি real order সম্পন্ন, প্রতিটির issue নোট করা।',
  },
];
